### ISSUE TITLE
Return result in search

### ISSUE THREAD

**Issue by davidbgeek** [AvatarHurden/keypirinha-currency#1]
Nice work! Would it be possible for you to make it so the currency conversion can be done directly in search, instead of having to go into the currency plugin first? Similar to how Calc does it where you can directly input numbers in search and the result displays in the results.

**Comment by AvatarHurden** [comment]
You can do this in the latest version (1.2). Simply type your conversion and, if you insert a valid query (at least one currency code), suggestions will appear.

Thank you for feedback!
