### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by kresbeatz** [AvatarHurden/keypirinha-currency#11]
Hi!

Last couple days I got Webservice failed (HTTP Error 429: Too Many Requests) error when using Convert Currency. Is there any solution how to avoid it?

Here is the the screenshot of this problem:
https://drive.google.com/file/d/1AMkKye_aAr1uOePoH-GzqwGDdUldLvBZ/view?usp=sharing

**Comment by AlennGK** [comment]
I can confirm.

**Comment by AvatarHurden** [comment]
This should be resolved for now, a server I own was having some troubles. I'll send an update in the next few days to allow people to avoid this issue in the future.
