### ISSUE TITLE
Webservice failed

### ISSUE THREAD

**Issue by kresbeatz** [AvatarHurden/keypirinha-currency#12]
Hi! Couple weeks ago I started experiencing "Webservice failed. The cache has failed. More information (and a fix) are available in the Currency plugin configuration file.". I checked the configuration file and didn't find anything that look wrong. It is the same config file as it was before when everything worked fine. Could you please look into this problem? Thanks in advance!
![keypirinha-x64_9gBhN0peLv](https://user-images.githubusercontent.com/34323574/115765843-8ae40f80-a3a7-11eb-8dc4-052f769733d8.png)

**Comment by AvatarHurden** [comment]
The cache is fixed now. That being said, the cache  can still fail in the future. The configuration file has a description of how you can create a free account for the API to get your own key and skip the cache layer (it's the last item in the [defaults] section).

**Comment by kresbeatz** [comment]
Thank you very much, I created free account and used API key, so everything is working great now. Thanks again!
