### ISSUE TITLE
Currency converter not working in Keypirinha 

### ISSUE THREAD

**Issue by aindriu80** [AvatarHurden/keypirinha-currency#3]
hi,

The currency converter is not working in Keypirinha.  Usually I just have to type 100gbp and the appropriate amount would come up in Euro.

![curr_keypirinha](https://user-images.githubusercontent.com/8885837/43635277-805fcf3c-9706-11e8-97f0-11e5e4b8c9de.png)

Any ideas ?

**Comment by aindriu80** [comment]
it working again, someone said it might have been the webservice

**Comment by polyvertex** [comment]
@aindriu80 note that if the screenshot is the content of your .ini file, it seems to miss the **required** `[defaults]` section line at the top of it.

**Comment by aindriu80** [comment]
It's not working again ? 

I added the [defaults] but no difference.

https://i.imgur.com/PJHzrZk.png

it must be the webservice off.

**Comment by polyvertex** [comment]
@aindriu80 it was just a general remark about .ini file format in KP, not directly related to the issue or this plugin in particular :)

**Comment by aindriu80** [comment]
no problem, thanks for the help ;)

**Comment by AvatarHurden** [comment]
Sorry for the delay in responding, but the issue really was with the API.

The Yahoo Finance API seems to have been shut down, so I replaced it with another currency API. This fixes the issue for now, but, since this API only allows 1000 requests per month with the free tier, I might have to look for another solution if the demand is too high.

**Comment by AbhishekTripathi** [comment]
![image](https://user-images.githubusercontent.com/1847545/116823748-85947b00-ab86-11eb-831c-6ce244121560.png)

Looks like the issue with the exchange rate provider has crept in again. For the past couple of days, I am getting the above error. Also, from the console, the following error is recorded:
```
ERROR: Currency.Currency: No OpenExchangeRates App ID declared in the configuration file
```

**Comment by AbhishekTripathi** [comment]
Never mind, I found the resolution to it in the configuration. I have fixed this by registering and using my own custom app id.

```
# A custom OpenExchangeRates App ID to use whenever the cache layer fails.
# If this is not specified, the plugin will only use the cache layer, which has
# no guarantees to work.
#
# You can create an account at https://openexchangerates.org/signup/free
# in order to get an App ID. The free layer should be sufficient for most users.
#app_id = YOUR_APP_ID
```
