### ISSUE TITLE
List index out of rang exception in Currency (v1.3, Keypirinha v2.19, v2.18)

### ISSUE THREAD

**Issue by DrorHarari** [AvatarHurden/keypirinha-currency#4]
Hi,

I am getting:

> 11:11:09.056 Plugin loaded: Currency.Currency (instance #2)
> 11:35:36.940 Apps.StartMenu: Cataloged 286 items in 0.0 seconds
> 12:51:36.672 Plugin loaded: Currency.Currency (instance #3)
> 12:51:36.690 ** ERROR: Error from Currency.Currency.on_catalog: <class 'IndexError'>: list index out of range
> Traceback (most recent call last):
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 94, in on_catalog
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 228, in _create_translate_item
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 226, in joinCur
> 

I tried to fix joinCur by changing the code to:
```
        def joinCur(lst):
            if type(lst) is list: 
                if len(lst) == 1:
                    return lst[0]
                elif len(lst) == 0:
                    return 'JPY'
                else:
                    return ', '.join(lst[:-1]) + ' and ' + lst[-1]
            else:
                return lst
```

But this just shows it is trying to convert JPY to JPY and not really operating in the box.

Any idea?

Thanks,

Dror

**Comment by DrorHarari** [comment]
Pretty lame there:

> [defaults]
> input_cur = USD
> output_cur = EUR

Could it be something with the service? I am running from Israel -- maybe there is a block? Is this code happening before or after connection to the service?

**Comment by polyvertex** [comment]
Hi! Same error here! With default config.

**Comment by AvatarHurden** [comment]
Ok, I think I found the bug. It should be fixed in v1.3.1.

If the problem happens again, please let me know and I'll reopen the issue. 😄

**Comment by DrorHarari** [comment]
Thanks @AvatarHurden , it works for me now. Just one note - maybe it's expected but initially the update did not work, I got the following exception:

> 01:23:50.377 PackageControl.PackageControl: Package up to date: keypirinha-currency
> 01:27:23.456 Plugin loaded: Currency.Currency (instance #2)
> 01:27:23.468 ** ERROR: Error from Currency.Currency.on_start: <class 'TypeError'>: __init__() takes 3 positional arguments but 4 were given
> Traceback (most recent call last):
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 75, in on_start
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 284, in _read_config
> 01:27:23.472 ** ERROR: Error from Currency.Currency.on_catalog: <class 'AttributeError'>: 'NoneType' object has no attribute 'last_update'
> Traceback (most recent call last):
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 97, in on_catalog
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 218, in _update_update_item
> 01:27:25.247 ** ERROR: Error from Currency.Currency.on_suggest: <class 'AttributeError'>: 'NoneType' object has no attribute 'validate_codes'
> Traceback (most recent call last):
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 108, in on_suggest
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 203, in _parse_and_merge_input
> 01:28:24.936 ** ERROR: Error from Currency.Currency.on_suggest: <class 'AttributeError'>: 'NoneType' object has no attribute 'validate_codes'
> Traceback (most recent call last):
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 108, in on_suggest
>   File "C:\Util\Keypirinha\portable\Profile\InstalledPackages\Currency.keypirinha-package\currency.py", line 203, in _parse_and_merge_input
> 

I did the update with PackageControl. I had to actually close and restart Kepirinha to get it to work.

Thanks!

**Comment by AvatarHurden** [comment]
I think that might be an issue with Keypirinha and Live Reload of packages, but I'll look into it. 👍
