### ISSUE TITLE
simple expressions not working ?

### ISSUE THREAD

**Issue by tchokido** [AvatarHurden/keypirinha-currency#8]
![image](https://user-images.githubusercontent.com/12753232/52422771-06bf4d80-2af7-11e9-8927-a09d147d9c01.png)

**Comment by DrorHarari** [comment]
Write:
5 USD

It will give you:
![image](https://user-images.githubusercontent.com/1831901/52425971-c61b0080-2b05-11e9-9bce-94f85c684b1b.png)

The Currency plugin is very useful but needs some work on edge cases.

**Comment by tchokido** [comment]
ok, so the exemple from the README is not relevant anymore?
Great plugin anyway :)

**Comment by AvatarHurden** [comment]
Hi @tchokido, thanks for opening an issue.

The input you tried should work, and I've found the bug that is causing the issue. Unfortunately, I am currently on vacation and can't release an update to fix the problem.

As a temporary solution, however, you can go into the configuration file and create a "separators" field with the default values. This should fix the issue until I can release a proper fix in an update.

Let me know if it works!

**Comment by AvatarHurden** [comment]
This should work in the newest version (2.1) without having to mess with the configuration file
