### ISSUE TITLE
Lost copy result to clipboard functionality

### ISSUE THREAD

**Issue by DrorHarari** [AvatarHurden/keypirinha-currency#9]
When I enter a number and currency like "12 USD" I get a list of currencies and the value of 12 USD in those currencies:

![image](https://user-images.githubusercontent.com/1831901/54477475-e29b0e80-4810-11e9-8602-c182eb444915.png)

I expect to be able to move to one of them and hit Enter to copy the numeric value to the clipboard but it does not work. Here I moved to the Euros and hit Enter (same with Tab) and I got:

![image](https://user-images.githubusercontent.com/1831901/54477513-46bdd280-4811-11e9-9265-3f14051127f4.png)

Here I can press Enter or Tab or whatever but I stay in the same place and the value is not copied, as expected, to the clipboard.

**Comment by AvatarHurden** [comment]
Hi @DrorHarari 

This should be fixed in the newer version. I also added a new option to copy the whole conversion as an equation, showing the sources and result together. 

Let me know if there are any other issues!

**Comment by DrorHarari** [comment]
Hi Arthur. Thanks for the quick fix - it is almost perfect 😎

What would make it perfect is to allow me to decide what would be copied on the default suggestion I get when typing (for example) "12 USD". Now what's copied (if I'm positioned on the Euro) is "10.61 EUR" which is not so helpful in Excel or in Calc (true, I don't use it but as an example). The menu after the tab let me choose if to copy with or without the unit.

One good option is to have it a configurable option, maybe add a config option CopyActionPreference with possible values like: CopyNumber / CopyNumberAndUnit / CopyConversion / CopyLast (the CopyLast makes my last specific selection sticky).

Anyway, thanks. /d
